version: '3'
services:
  worker:
    build: .
    image: awesome_isp_worker
    command: [celery, worker, --app=awesome_isp_celery, --loglevel=info]
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - READ_COMMUNITY=readonly
      - MONGO_HOST=mongodb://mongo:27017
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  rabbitmq:
    image: rabbitmq:3-management