version: '3'
services:
  worker:
    build: .
    image: &img awesome_isp_worker
    command: [celery, worker, --app=worker.app, --pool=gevent, --concurrency=20, --loglevel=info]
    environment: &env
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - READ_COMMUNITY=readonly
      - MONGO_HOST=mongodb://root:example@mongo:27017
      - SCHEDULE_TIME=300.0
      - NETWORKS_TO_DISCOVER=10.99.192.0/24,172.17.88.0/24
    depends_on:
      - rabbitmq
      - beat
      - mongo
    restart: 'no'
    volumes:
      - ./awesome_isp_celery:/app

  beat:
    build: .
    image: *img
    command: [celery, beat, --app=worker.app, --loglevel=info]
    environment: *env
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
      - ./awesome_isp_celery:/app

  flower:
    build: .
    image: *img
    command: [celery, --app=worker.app, flower]
    environment: *env
    depends_on:
      - worker
    restart: 'no'
    ports:
      - "5555:5555"
    volumes:
      - ./awesome_isp_celery:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  rabbitmq:
    image: rabbitmq:3-management